### ISSUE TITLE
How does this extension work?

### ISSUE THREAD

**Issue by JT-Potato** [rospino74/Quizlet-Bypass#100]
Hi! Just wanted to know how this extension works. As you might be aware, Quizlet has put almost all of its functions behind a paywall... I've just tried the extension out, and after changing the manifest.json to fix some errors, it doesn't work for those situations...

Would be quite useful if you could explain what the extension does, and I'd be more than happy to contribute.

**Comment by rospino74** [comment]
Basically, it creates a new account via the Quizlet API, which cheekily doesn't implement any captcha challenge:
https://github.com/rospino74/Quizlet-Bypass/blob/481a1e834c8b7f3a1ea2b5df5274affb144847d7/src/foreground/quizlet/import/accountMaker.js#L29-L47

And then set the cookies for the page with the newly created session token:
https://github.com/rospino74/Quizlet-Bypass/blob/481a1e834c8b7f3a1ea2b5df5274affb144847d7/src/background/cookieReplacer.ts#L20-L24

At the moment I am also thinking of a way to bypass a possible captcha.
