### ISSUE TITLE
Cannot Use extension with chrome

### ISSUE THREAD

**Issue by flamerds** [rospino74/Quizlet-Bypass#105]
Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.
If I put a version in, it says it cannot find backgrounds.js

**Comment by rospino74** [comment]
Can you please provide me with more details like the browser, the extension version and how you installed it?

Also, try installing the [latest build snapshot](https://github.com/rospino74/Quizlet-Bypass/suites/5436999163/artifacts/172416535) and see if it still have the issue.
