### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nicholasdipoalo** [rospino74/Quizlet-Bypass#106]
I don't know anything about code or Github. I just downloaded the 1.4.2 file and loaded it into google chrome but it came up with an error and I still can't get past the paywall. I assume it's an easy fix, but I don't know what I'm doing. 
![Screenshot (158)](https://user-images.githubusercontent.com/81546835/155007150-a02bc04a-5151-472c-9632-ef10b761a540.png)
![Screenshot (157)](https://user-images.githubusercontent.com/81546835/155007149-b68baaa8-251c-4886-a27d-2a34f3fc940b.png)
![Screenshot (155)](https://user-images.githubusercontent.com/81546835/155007147-97a5f395-9a44-4878-a5c2-a88c8f4ae156.png)

**Comment by rospino74** [comment]
I tried to address the problem so please try this version out:
[extension-bc94a10.zip](https://github.com/rospino74/Quizlet-Bypass/files/8135465/extension-bc94a10.zip)
Try it on [this page](https://quizlet.com/explanations/textbook-solutions/discrete-mathematics-and-its-applications-7th-edition-9780073383095/chapter-1-exercises-46-dff2792f-8ec5-4ee8-bdf3-1972a7b9a8e6) where I prove it to work

The `browser_specific_settings` error is a false positive as the key is required on Firefox.
