### ISSUE TITLE
Manifest file is missing 

### ISSUE THREAD

**Issue by shadizghe** [rospino74/Quizlet-Bypass#112]
Hello ! 

Whenever I try to unload the package on google chrome, it says manifest file is missing. maybe it's a JSON file issue ?

**Comment by rospino74** [comment]
Could you please send me more details about your problem? Like the manifest file or the file tree hierarchy
Is [this build](https://github.com/rospino74/Quizlet-Bypass/suites/5491845745/artifacts/175483712) still affected by the issue?

**Comment by shadizghe** [comment]
Thank you soo much ! the manifestation file that you provided solved the issue. I just unloaded the files in main quizletbypass folder. Now it;s working perfectly
