### ISSUE TITLE
Manifest V3

### ISSUE THREAD

**Issue by NickSei** [rospino74/Quizlet-Bypass#113]
## Platform informations
- Chrome, Edge
-  V1.4.2
-

## Issue Description
Manifest version 2 is deprecated, and support will be removed in 2023

### Actual behaviour
I cannot use the extension

![image](https://user-images.githubusercontent.com/68117224/156868149-80befb9a-bdf4-451e-af31-ebf380df62fa.png)

**Comment by rospino74** [comment]
At the moment it is still possible to use `MV2` extensions in Chrome. Now I'm just trying to figure out how to successfully migrate the extension as many things have changed and Mozilla has no plans to support `MV3`.

**Comment by rospino74** [comment]
Updates in #240
