### ISSUE TITLE
Hey how can i solve this

### ISSUE THREAD

**Issue by ManiSyan** [rospino74/Quizlet-Bypass#119]
<img width="578" alt="Screenshot 2022-03-19 124456" src="https://user-images.githubusercontent.com/92694531/159112577-e9f98310-9c39-4f38-8234-1652aa5e9b05.png">

**Comment by rospino74** [comment]
Those are just warnings. You can still use the `MV2` version until [January 2023](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/).

**Comment by ManiSyan** [comment]
Thank u so much for ur response and also thanks for extension i want to ask one thing that sir if u know any method or extensions or script for unblur chegg answers please let me know it will be very helpfull for me Thank u.
