### ISSUE TITLE
Extension doing nothing

### ISSUE THREAD

**Issue by frogsinatra** [rospino74/Quizlet-Bypass#124]
Are there any specific steps you need to follow in order to make the extension work? I downloaded the chrome extension, unzipped the file, and then installed it as specified in the instructions but after installation not change has occurred when attempting to access quizlet explanations.

**Comment by rospino74** [comment]
Can you provide me with additional details? Like if the extension is loaded correctly or some errors shows up?

**Comment by Cynrode** [comment]
"browser_specific_settings": {
    "gecko": {
      "id": "quizletbypass@rospino74.github.io",
      "strict_min_version": "48.0",
      "update_url": "https://github.com/rospino74/Quizlet-Bypass/raw/master/public/updates.json"
    }
  },
![facts](https://user-images.githubusercontent.com/102715210/161477412-7ae7ee5f-3994-4a92-bad8-c50d53c607c8.PNG)


Chrome Error reads, "Unrecognized manifest key 'browser_specific_settings'.

**Comment by rospino74** [comment]
That are just warnings. Is the issue still reproducible on [this version](https://github.com/rospino74/Quizlet-Bypass/releases/download/v1.4.3/extension.zip)?
