### ISSUE TITLE
400 Bad Request Error when clicking on a a problem

### ISSUE THREAD

**Issue by nickinternet** [rospino74/Quizlet-Bypass#137]
so i followed all the instructions and everything but when i click on a problem to get the steps to answer it it gives me this error. please hel
![download](https://user-images.githubusercontent.com/104537042/165648965-591daa63-3cb0-4a69-a9c8-be83c0518179.png)
p

**Comment by rospino74** [comment]
Could you please send me the textbook url?

**Comment by memreasan** [comment]
Just delete the cookies as shown in the attachment below and reload the site.  Click the lock image to the left of quizlet.com and click "Cookies" there afterwards.
![image](https://user-images.githubusercontent.com/105994059/196064017-982ae26f-e0a5-4cde-b5b2-54e17f6a0edd.png)
