### ISSUE TITLE
Doesn't work both in Chrome and Firefox

### ISSUE THREAD

**Issue by memreasan** [rospino74/Quizlet-Bypass#198]
## Platform informations
- Chrome, Firefox
- Extension version (e.g. 1.4.2)
- [ ] Manually built extension

## Issue Description
The extension doesn't work in Chrome, so I tried to install it in Firefox and even though I set the "xpinstall.signatures.required" to **false**, I can't install the add-on. The Chrome extension successfully switches between different accounts but it doesn't bypass any paywalls.

### Actual behavior
![image](https://user-images.githubusercontent.com/105994059/194785237-48d67746-3f00-48e6-ba90-9aec6c9c0e6f.png)
![image](https://user-images.githubusercontent.com/105994059/194785278-82ee666e-627f-456b-99f5-fe8e56eccef3.png)

### Expected behavior
I need some guidance because it clearly doesn't work for me and does for others.

### Steps to reproduce
I personally followed the directions on the main page.

**Comment by rospino74** [comment]
Quizlet randomly shows this hard paywall.  The extension must then reload the page until it gets one without it.
Please try [this snapshot](https://github.com/rospino74/Quizlet-Bypass/suites/8722255474/artifacts/394306424). Please, tell me if the issue is still present.

**Comment by gavincaul** [comment]
I tried with the snapshot you provided, seemed to have not fixed the issue. Been reloading for abt 5 mins now

**Comment by memreasan** [comment]
UPDATE: I tried with the snapshot you uploaded and it seems to be working right now. I will give another update after I use it for a while. Thank you for the help @rospino74.
