### ISSUE TITLE
400 request header or cookie too long

### ISSUE THREAD

**Issue by KCMsaum** [rospino74/Quizlet-Bypass#201]
not working now
i was working before today

**Comment by memreasan** [comment]
Just delete the cookies as shown in the attachment below and reload the site.  Click the lock image to the left of quizlet.com and click "Cookies" there afterwards.
![image](https://user-images.githubusercontent.com/105994059/196064017-982ae26f-e0a5-4cde-b5b2-54e17f6a0edd.png)
