### ISSUE TITLE
Extension does not let me access paywalled study sets after 5 free tries

### ISSUE THREAD

**Issue by TheOneTEM** [rospino74/Quizlet-Bypass#215]
## Platform informations
- Browser: Chrome
- Extension version: Latest
- [ ] Manually built extension

### Actual behaviour
Quizlet does not let me proceed past the free 5 rounds in Learn mode, despite following the correct installation steps.

### Expected behaviour
Quizlet should allow me to progress past 5 rounds in Learn mode.

### Steps to reproduce
Steps to reproduce the behaviour:
1. Clear the "trial" 5 rounds on any study set long enough to not finish Learn after the free rounds
2. Clear browser history, cookies and cached dat
3. Install extension via instructions on repo page
4. Log in to Quizlet
5. Enter the study set you did the "trial" on, it should continue being locked

**Comment by rospino74** [comment]
As I said in https://github.com/rospino74/Quizlet-Bypass/issues/191#issuecomment-1299157777, only textbook solutions can be unlocked by this extension. Other features cannot be unlocked because Quizlet hard-paywalls them.

_(This will also close #183)_
