### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by 3DKingdom** [rospino74/Quizlet-Bypass#229]
## Platform informations
- Browser (e.g. Chrome, Edge, Firefox...)
- Extension version (e.g. 1.4.2)
- [ ] Manually built extension
chrome using install instructions on the github

### Actual behaviour
account changes but it doesnt block the paywall
A clear and concise description of what the issue is.
Please provide screenshots, stack traces or source code references if needed

### Expected behaviour
paywall needs to be blocked
### Steps to reproduce
Steps to reproduce the behaviour:
1. Go to this place https://quizlet.com/explanations/questions/how-are-photosynthesis-and-cellular-respiration-related-9de9020d-59e8-4de0-8b71-d4b32a4fd199
2. Paywall isnt blocked
3. See the bug
google says the error Unrecognized manifest key 'browser_specific_settings'.

**Comment by rospino74** [comment]
Please see #215 for the paywall and #134 for `browser_specific_settings`
