### ISSUE TITLE
Manifest Version 3 (Google Chrome 2023)

### ISSUE THREAD

**Issue by Fernandes1120** [rospino74/Quizlet-Bypass#240]
## Platform informations
- Browser (Chrome)
- Extension version (1.4.5) Latest
- [ ] Manually built extension

## Issue Description

Chrome no longer supports Manifest version 2, and thus this extension is no longer supported.

### Actual behaviour
Bypass no longer works, 400 bad request error, can't reload page

### Expected behaviour
Reload page, new quizlet account, bypass paywall, accessing answer on selected page

### Steps to reproduce
Steps to reproduce the behaviour:
1. Open quizlet.com
2. Find a textbook in the search bar and open a problem within a chapter
3. After selecting multiple problems, paywall is reached
4. Extension attempts to relog into different account
5. Account **does not** change, after multiple reloads, chrome prompts user with error 400
6. No further resolutions to bypass paywall

**Comment by rospino74** [comment]
Yeah, I know 😞. there are still some problems with MV3. I've made some progress in the [feature/manifest-mv3](https://github.com/rospino74/Quizlet-Bypass/tree/feature/manifest-v3) branch. You can download a **very unstable** build [here](https://github.com/rospino74/Quizlet-Bypass/suites/10318941303/artifacts/507670417).
