### ISSUE TITLE
400 Bad Request Request Header Or Cookie Too Large nginx

### ISSUE THREAD

**Issue by spidey-program** [rospino74/Quizlet-Bypass#283]
## Platform informations
- Browser (e.g. Chrome, Edge, Firefox...)
- Extension version (e.g. 1.4.2)
- [ ] Manually built extension

### Actual behaviour
A clear and concise description of what the issue is.
Please provide screenshots, stack traces or source code references if needed

### Steps to reproduce
Steps to reproduce the behaviour:
1. Go to this place
2. Perform that action
3. ...
4. See the bug

**Comment by rospino74** [comment]
Just try to delete the cookies and reload the site.

On **Chrome** click the lock image to the left of the address bar, click _Cookies_ and delete all of them.
