### ISSUE TITLE
Extension is not working and there is a bug

### ISSUE THREAD

**Issue by tylerpak18** [rospino74/Quizlet-Bypass#359]
![image](https://github.com/rospino74/Quizlet-Bypass/assets/136657527/609a5379-7561-4483-b4ec-950168dd71b6)

![image](https://github.com/rospino74/Quizlet-Bypass/assets/136657527/c65bd6d4-b869-4677-946f-49abdc93b79c)

There is an error message for the extension. So please fix it.

**Comment by rospino74** [comment]
Please check if [this build](https://github.com/rospino74/Quizlet-Bypass/suites/14132030301/artifacts/791263608) works.

**Comment by tylerpak18** [comment]
It works. Thank you! :D
