### ISSUE TITLE
The extension randomly doesn't log you in

### ISSUE THREAD

**Issue by whitehorsewithsun** [rospino74/Quizlet-Bypass#360]
it just does not work here.
![1688724439916](https://github.com/rospino74/Quizlet-Bypass/assets/138870651/94b54e44-7b06-4ac3-9cd4-32dc3325166b)
it randomly works for several time and break down. i do not know if i should point at what place to start it. it seems like it have not start to work. even it help me to sign in an account, it stop to continue then.

**Comment by rospino74** [comment]
Please check if [this build](https://github.com/rospino74/Quizlet-Bypass/suites/14132030301/artifacts/791263608) works

**Comment by whitehorsewithsun** [comment]
I am sorry but it seems like it still keeps the same with the new extension. Accidentally it helps to log in an account, but it stops to work from then.

**Comment by drinktoomuchsax** [comment]
its same for me that "randomly" work, but the probability is acceptable. make sure you did login your account and when it doeent work, just simply refresh your page.

**Comment by whitehorsewithsun** [comment]
so, when I am using it, I need to log in first?

**Comment by swamjinwoo** [comment]
> Please check if [this build](https://github.com/rospino74/Quizlet-Bypass/suites/14132030301/artifacts/791263608) works

404 The website doesn't; exist. Could you upload the build again?

**Comment by rospino74** [comment]
@swamjinwoo try this one https://github.com/rospino74/Quizlet-Bypass/suites/14132030301/artifacts/793569771

**Comment by drinktoomuchsax** [comment]
> so, when I am using it, I need to log in first?

after trying this on myself, feels like something have changed since last time i use.
it works will without log in, but you may need to be patient waiting the plugin load.

**Comment by swamjinwoo** [comment]
> @swamjinwoo try this one https://github.com/rospino74/Quizlet-Bypass/suites/14132030301/artifacts/793569771

worked for me. thank you

**Comment by whitehorsewithsun** [comment]
it is better now. maybe i should not try so many time and waiting patiently is useful.
