### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by miniquinox** [rospino74/Quizlet-Bypass#395]
## Platform informations
- Browser Chrome
- Extension version 1.5.2
- [ ] Manually built extension

### Actual behaviour
The website refreshes time after time. 

### Expected behaviour
It should just show me the answers

### Steps to reproduce
Followed installation instructions for chrome on windows 11 using chrome

**Comment by rospino74** [comment]
Could you please provide me with the URL you are visiting?

**Comment by miniquinox** [comment]
https://quizlet.com/explanations/questions/an-efficiency-study-of-the-morning-shift-at-a-certain-factory-indicates-that-an-average-worker-who-i-fd301704-5924-4f27-9513-494ca6abff40

**Comment by rospino74** [comment]
I'm sorry, but as I said in the [readme](https://github.com/rospino74/Quizlet-Bypass/blob/master/README.md#additional-notes-%EF%B8%8F) and in #215, this extension can only unlock textbook solutions. Other services are hard-paywalled and can be unlocked only by purchasing Quizlet Plus.
