### ISSUE TITLE
wont even let me load it

### ISSUE THREAD

**Issue by mthril** [rospino74/Quizlet-Bypass#417]
im using brave which uses chromes brower and when i press load unpack i try all of the files but none of them work with them all saying manifest file is not found. What is the name of the folder with the extension cause i don't think im doing it right but it just does not work at all

**Comment by rospino74** [comment]
Does the unzipped folder look like this?
![immagine](https://github.com/rospino74/Quizlet-Bypass/assets/34315725/218b5661-f5f1-4b1b-ae65-4378b038c045)
Because it seems that Brave can't find `manifest.json`.

**Comment by mthril** [comment]
I fixed it my thing kept unzipping it weird
