### ISSUE TITLE
Paywall blocker not functioning. Errors:

### ISSUE THREAD

**Issue by joehannsenn** [rospino74/Quizlet-Bypass#436]
### Browser Version

Chromium (Brave)

### Exension Version

1.5.3

### Actual behaviour

Stopped working suddenly (when I happened to open up the GitHub page for the extension to share with a friend). I'm getting stuck behind the quizlet paywall again.

Here are the errors it threw for me:

Unrecognized manifest key 'browser_specific_settings'.
%cError while fetching the page: %o color: #F5AB80 Error
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')

### Reproduction steps

The errors pop back up immediately as soon as I reload quizlet.

### Expected behaviour

.

**Comment by rospino74** [comment]
Can you try [this build](https://github.com/rospino74/Quizlet-Bypass/suites/17377302454/artifacts/993076737)? It has debug prints on so the logging will be a little more detailed

**Comment by joehannsenn** [comment]
I'm not sure I'll be of much help. I restarted my computer and haven't been
able to reproduce the issue since. My computer often has issues that
require a restart to resolve, so I expect the problem is just that I bought
an HP laptop, hahaha.

**Comment by joehannsenn** [comment]
If it gets stuck again though, I'll try out the debug build.
