### ISSUE TITLE
"Upstream Request Timeout" error on Firefox Nightly

### ISSUE THREAD

**Issue by SourasishBasu** [rospino74/Quizlet-Bypass#475]
### Browser Version

Firefox Nightly

### Exension Version

1.5.4

### Actual behaviour

Going to any quizlet link redirects to the cloudflare human check and then never loads the actual website. Instead displays "upstream request timeout"

These console logs are shown.
![image](https://github.com/rospino74/Quizlet-Bypass/assets/89185962/23a6616d-8b6f-4801-85b9-57658799ec65)

### Reproduction steps

1. Go to any quizlet textbook link such as: https://quizlet.com/explanations/textbook-solutions/probability-and-statistics-for-engineering-and-the-sciences-9th-edition-9781305251809

### Expected behaviour

Normally the page should be loading the textbook solutions.

**Comment by rospino74** [comment]
Quizlet servers are offline at the moment. The only thing we can do is wait.

[![Downdetector](https://github.com/rospino74/Quizlet-Bypass/assets/34315725/8be8a695-8c6a-438a-bced-9fffd50ee663)](https://downdetector.com/status/quizlet/)
